sudo: true
dist: trusty
language: node_js
git:
  depth: 3
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_8a574547e2eb_key -iv $encrypted_8a574547e2eb_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
- travis_retry make install
- travis_retry sudo pip install Pygments
script:
- make deploy
