---
branches:
  only:
  - master
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_8a574547e2eb_key -iv $encrypted_8a574547e2eb_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- ssh-add deploy_key
install:
- make install
- pip install Pygments
script:
- make deploy
