---
sudo: true
dist: trusty
language: node_js
git:
  depth: 3
branches:
  only:
  - master
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_8a574547e2eb_key -iv $encrypted_8a574547e2eb_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- ssh-add deploy_key
install:
- cp _custom.scss bootstrap/scss/_custom.scss
- cd bootstrap
- nvm install 4
- npm install -g npm@3
- node --version
- npm --version
- nvm --version
- bundle install --deployment --jobs=3 --retry=3
- cp grunt/npm-shrinkwrap.json ./
- npm install
- ls -ltr dist
- grunt
- ls -ltr dist
- cd ..
- cp -rv bootstrap/dist/css/* themes/roidelapluie.be/static/css
- cp -rv bootstrap/dist/js/* themes/roidelapluie.be/static/js
- make install
- pip install Pygments
script:
- make deploy
