name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    env:
      HUGO_VERSION: 0.54.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
          tar xf hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz hugo
      - name: Build
        run: hugo --minify
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./public
